import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/Header/Header";
import StoreProvider from "@/components/StoreProvider/StoreProvider";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <StoreProvider>
      <html lang="ua">
        <body>
          <Header />
          {children}
        </body>
      </html>
    </StoreProvider>
  );
}
