import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/Header/Header";
import StoreProvider from "@/components/StoreProvider/StoreProvider";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <StoreProvider>
      <html lang="ua">
        <head>
          <link rel="preconnect" href="https://fonts.googleapis.com"></link>
          <link
            rel="preconnect"
            href="https://fonts.gstatic.com"
            crossOrigin="anonymous"
          ></link>
          <link
            href="https://fonts.googleapis.com/css2?family=Onest:wght@100..900&display=swap"
            rel="stylesheet"
          ></link>
        </head>
        <body>
          <Header />
          {children}
        </body>
      </html>
    </StoreProvider>
  );
}
