import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/Header/Header";
import StoreProvider from "@/components/StoreProvider/StoreProvider";
import { Onest } from "next/font/google";

const onest = Onest({
  subsets: ["latin"],
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <StoreProvider>
      <html lang="ua" className={onest.className}>
        <body>
          <Header />
          {children}
        </body>
      </html>
    </StoreProvider>
  );
}
